### ISSUE TITLE
Review/Test fork()

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#10]
Fork was implemented and merged last year, but we're not sure about how robust it is.

PRs:
https://github.com/Lind-Project/native_client/pull/5
https://github.com/Lind-Project/native_client/pull/6

Review code changes and testing implementation to assure that all of this is correct.

**Comment by rennergade** [comment]
Upon further testing, the Repy side of Lind seems to not acknowledge separate processes at all. I'm not sure if this is just not implemented, or by design. This makes doing file operations between forks not POSIX compliant/buggy. This of course also pertains to how pipes are handled.

We brainstormed some solutions in the meeting today, such as transmitting the pid/cageid via the RPC calls, but are looking for some more clarity. 

@JustinCappos @moyix

**Comment by JustinCappos** [comment]
I'm confused about the issue you describe.  Is the problem here conceptual
or is there an implementation issue?

**Comment by rennergade** [comment]
Conceptually, I want to confirm that we should implement process book-keeping on the Repy side. I wasn't sure if I was missing a theoretical reason that wasn't happening, or if it just wasn't tackled yet.

Implementation-wise, does:
1. Transmitting pid/cageid through the RPC calls
2. Storing things such as each `filedescriptortable` in a dictionary keyed by PID seem reasonable?

**Comment by JustinCappos** [comment]
I'm not sure where you need to transmit a pid/cageid at.  Can you explain
more what you mean by RPC?

Yes, we do want to key the SafePOSIX microkernel data structures by pid /
cageid as you describe.

**Comment by rennergade** [comment]
Great!

The entire implementation of fork() (as well as a few other system calls such as exec) as well as the caging implementation lives inside NaCl. Since this was originally implemented as only being for one process, Repy never needed to know the pid or do any process related book-keeping, such as separate file descriptor tables.

All of the system calls in Repy are triggered by NaCl calling “CallPythonFunc” to call LindSyscall in Repy (I considered this a remote procedure call, is that the wrong nomenclature?). My inclination is that the "easiest" way to deal with this is to also send id's in that call.

**Comment by JustinCappos** [comment]
I see.  Sure this would be fine.  Somehow the system needs to know the PID
of the caller.  Do you get its memory location and use this to derive the
PID?

FYI: It's a good idea to keep in mind that a PID that is given to a
"microprocess" (the thing we are running in a cage) is permanent and
unique.  However, the location of a microprocess in memory may in theory
change as we do more research in the future.  So, if you only have a way to
know the memory location a call comes from, it is worth keeping a table
that translates this to PID first before indexing the microkernel data
structures by PID (instead of directly doing this by memory address).  If
you don't translated to PID and then index using PID, then there will be a
mess to clean up when we implement SSI / migration functionality.

**Comment by rennergade** [comment]
There's still a few quirks here that are going to get updated in the pipe merge. Leaving open for now.
