### ISSUE TITLE
Implement CoW LKM for Fork

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#109]
Per https://github.com/Lind-Project/lind_project/issues/67

We've improved Fork performance by 10x but there may be further improvements. One of the first things to try would be making it so we don't have to revalidate files on every fork.

**Comment by jesings** [comment]
Currently, fork runs at 30x slower than native. This is a significant improvement from the 2000x slower original implementation, but still a far cry from anything terribly usable. Considering I was theoretically doing less copying than the native implementation, I was extremely puzzled as to why our implementation was still so much slower. Looking into the remaining costs, around a third of the time we were spending was in NaClPatchAddr, however the other two thirds was nearly entirely copy time. I went digging into the documentation, which seems to say that process_vm_writev does not actually perform significantly better than a memcpy when transferring memory within a single process, and is primarily useful for transferring memory between processes, and that it doesn't actually do copy on writ. Seeing as to how the documentation for splice seems to say that it explicitly does do copy-on-write, at least in certain cases, I updated my old splice implementation with all the new improvements I made, however it still performed slightly worse than the process_vm_writev. It appeared to be doing copy-on-write from memory to the pipe when vmsplice was called, but appeared not to be doing copy-on-write when splicing from the pipe to our memory backing file. When I looked into the kernel code to see why this was happening, I believe I found out that splice can not do copy-on-write from a pipe to a file unless there is specifically a handler defined for it in the kernel (or perhaps in fuse), as the generic handler just called generic write which essentially performs a memcpy, despite the fact that the documentation explicitly says it can (as far as I can tell, this feature was removed in linux 2.6.something because of a vulnerability found in it). At this point, and after significantly more research, it seems to me that the kernel does not expose any copy-on-write functionality to user space except for fork and kernel samepage merging, the first of which is useless to us because we can't move the pages between processes without incurring copy cost, and the second of which is useless to us because it requires the pages to be created already and then merges them later which is really counterproductive. 

After some preliminary discussions with @rennergade , we came to the conclusion that a loadable kernel module was feasible and was probably the only good way to solve this problem. I've been digging through the kernel source to see how I could add copy-on-write functionality in, and it seems eminently doable. We would probably accomplish this by intercepting the process_vm_writev system call and doing our own operation with it if some flag was set (the current API does not allow any flags to be set in the actual syscall) and if not calling the actual syscall. However, I was also thinking that even if we made copy time negligible through an LKM, we would still perform 10x worse than fork, and so our LKM should do 2 things: 1, add COW functionality to some syscall, and 2, hook a new fault handler into the page table entries that we create as COW, which will lazily NaClPatchAddr it when it's copied.

However, I soon realized that this was not possible, as reading or executing from pages would not trigger a CoW fault, and the reading/executing processes would get the incorrect cage bits in their addresses. Last week I tested removing NaClPatchAddr on a whim to see if it would break anything, and it didn't strictly break anything on my simple tests however it was clear that each child cage was executing code from the parent and thus was behaving incorrectly and breaking promises given by NaCl. Therefore, in order to make lind's fork perform in the same order of magnitude as native, I think 2 things would be necessary. 1: to make an LKM with CoW support, and 2: to change nacl-gcc so as to remove the need for NaClPatchAddr. I'm worried about the performance implications of 2, as it's definitely possible that by requiring explicit validation for fixed addresses in the inner loops of files, without intelligently taking them out of the loops, we could be adding significant performance cost that might for many applications outweigh the benefit of faster fork. The only other alternative I could think of is copy-on-read/write I think would be even worse for performance.

I'd like to hear what thoughts @moyix and @JustinCappos have on what the best path forward for all of this is or whether we even should continue trying to improve fork performance for the time being.

**Comment by JustinCappos** [comment]
> However, I soon realized that this was not possible, as reading or executing from pages would not trigger a CoW fault, and the reading/executing processes would get the incorrect cage bits in their addresses. 

As I understand it, this only should impact the way the upper bits of the addressed are masked.  The lower order masking should be the same:
and %eax, 0xffffffe0
jmp *%eax

If so, can we change the upper masking to read the cage's address mask from thread local storage (instead of an immediate operand) and then blit it?

**Comment by jesings** [comment]
It is my understanding of NaCl's SFI mechanism (which may well be incorrect) that this will only work for stack addresses and other addresses in memory, because I believe I read that jumps to fixed addresses in a validated executable are not masked by NaCl's compiler. This is the main thing I'm worried about here, and this is the main reason (I believe) why NaClPatchAddr is necessary for executable regions. This definitely warrants some exploration though. If it turns out that we can get by doing something like this to get rid of NaClPatchAddr, that would be great, I'm just a little worried if my understanding is correct about the cost of changing all those fixed jumps even in the inner loop of a program to masked indirect jumps.
I've been doing some other thinking regarding different ways we can handle this, and one thing that comes to mind for me is that we have one cage for executable memory only and one cage for all the other data. This would require 2 reserved registers for both cage masks, and I think it might create some problems with self-modifying code and mapping executable data and the like but I thought it would be interesting to consider, especially because it might give us a *more* performant fork than native. The big questions there are what the cost of taking away another register would be, and whether we could handle those PROT_EXEC problems.

**Comment by JustinCappos** [comment]
Let's look and see if relative jumps are used.  If so, this should still work just fine.  If not, maybe we can see how hard it would be to change NaCl to only emit relative jumps, etc.

**Comment by jesings** [comment]
Something interesting to note: everything NaClPatchAddr seems to do should be useless as far as I can tell, however that's not quite the case. I've disassembled a multiple fork test file that doesn't work right in order to see how things behave, and everything seems to be done correctly, both in the disassembly and in NaCl itself, despite the fact that changes to a variable in one cage clearly modify local variables in other cages. I have not tested global or static variables yet. Things that are not the culprit through disassembly and NaCl and testing.
- The cage bits in r15 are updated for each child
- The value of rbp and rsp are updated accordingly for each child based on the child cage bits on fork, so variable accesses on the stack work fine
- Popping rbp off the stack involves function epilogues like this:
  ```
  add    $0x28,%esp # why a fixed count is used rather than rbp/ebp I don't know
  add    %r15,%rsp
  pop    %rbx # just a callee-saved register
  pop    %r11
  mov    %r11d,%ebp
  add    %r15,%rbp
  ```
  followed by the standard return
  ```
  pop    %r11
  and    $0xffffffe0,%r11d
  add    %r15,%r11
  jmpq   *%r11
  ```
  which should have no chance of getting into another cage's address space
- all calls are handled correctly with the same kind of masking as returns

At this point, I am unsure of what the root cause of this issue is, and I'm nearly out of guesses. I have been starting to attempt watching memory accesses to the variable location, but it's annoying to do in gdb. It's going to be the next thing I try.

If anyone has any ideas for what might be causing these programs to break cage boundaries, I'd appreciate hearing them. It seems to be particularly caused by multiple forks.

One thing which would almost definitely fix this manifestation of the problem is masking around variable accesses that require rbp or rsp from NaCl-gcc but I'd like to find a different solution, as that is likely not only to be slow, but also to not fix the actual problem.

The following is an example of a small breaking test. The native version prints out 256 (255?) lines of "########" and the no NaClPatchAddr lind version prints out only 2 such lines and sometimes seg-faults in trusted code later, however this is a separate issue which is that the main thread exiting before the other threads may free some resources that are still needed. I'm nearly positive this is not a related issue as the program often doesn't seg fault and still only returns 2 lines of output.
```
int main() {
    int forkdepth = 8;
    while(forkdepth--) {
        if(fork() == -1) {
          puts("Fork failed");
          return -1;
        } else {
          putchar('#');
        }
    }
    putchar('\n');
}
```

**Comment by jesings** [comment]
I ran into various issues with trying to load the user program in as a symbol file, so I'm putting that on hold for now. Doing some print debugging, I noticed that the pid of these processes was being reported very incorrectly and the behavior of these programs was very wrong. Simplifying the test program even further, I made this:
```
#include <unistd.h>
#include <stdio.h>
int main() {
    int forkdepth = 3;
    while(forkdepth--) {
        fork();
        putchar('0' + (forkdepth % 10));
        fflush(stdout);
    }
    return 0;
}
```
Which in native returns
```
21210101000000
```
(2 twos, 4 ones, and 8 zeroes)
which is correct and which in lind returns 
```
221100
```
Further debugging indicated to me that this may be an error with writing to stdout after forks which does not trigger under certain debug conditions.

**Comment by jesings** [comment]
That error seems not to have been related to NaClPatchAddr removal, but rather NaClPatchAddr removal exacerbated a race condition that was already present and messing things up. This [pull request](https://github.com/Lind-Project/native_client/pull/42) addresses the main bug it was being caused by, and also makes NaClPatchAddr into a no-op, and it looks like everything works correctly when this is done.

**Comment by jesings** [comment]
Currently there are two remaining significant sources of overhead related to fork. The first is of course copy time, which we're trying to deal with with the LKM. I'm plodding through work on the LKM, and have managed to access kallsyms_lookup_name using kprobes, but I'm unlikely to get anywhere fast there without some direction, as I really don't know what I'm doing there. The second such source of overhead, which is perhaps half as much as copy time is reloading of the text segment from the executable. This is not only incorrect behavior but also is relatively slow. Copying it without a usable CoW would be a significant further penalty to runtime, as there's a lot of padding around the actual text segment that would be copied. I'll probably try to incur this penalty for now to unify everything such that the implementation of the CoW LKM will just be a drop in thing, however I'm not sure we want to require use of the LKM, and so I still think it might be worth looking at what can be copied there.

**Comment by JustinCappos** [comment]
Maybe it is time to fire off another email to the folks at IBM who do
kernel work and ask if they have expertise here.  It sounds like you'll be
working on other things for a short time and it could both pan out and also
remind them that we're all working together.

Please also let them know I'm grateful for the IBM faculty award.  :)

**Comment by jesings** [comment]
It probably makes sense to try contacting the people at IBM again because this does seem right up their alley.
Furthermore, I've gotten pretty stuck working on the LKM. The current problem I'm trying to deal with is a deadlock issue related to the Linux kernel function copy_page_range, which does the brunt of the actual copy-on-write stuff in fork.
This function, in recent kernels, takes two vm_area_structs--the one you want to copy out of (the remote vma), and the one you want to copy into (the local vma), (in older kernels the semantics were different but the issue still remains). Each of these vm_area_structs contain a reference to the memory map of the process they're associated with. These memory maps have a pthread_rwlock read/write lock (in older kernel versions it was just a semaphore with read-write helper functions), which can take unlimited readers but only a single writer, and which is extremely deadlock prone--i.e. if you try to acquire the readlock if the writelock is acquired, you deadlock. This is exactly the situation we get in copy_page_range: a function called by it asserts that the writelock on the local memory map is held so this must be locked before calling copy_page_range, however within copy_page_range (or rather a function called by it), the read lock of the remote memory map is acquired, causing an unavoidable deadlock state in our case where we're copying within the same process It is reasonably dubious at this point whether copy_page_range, or very much pre-existing kernel CoW functionality at all can really be leveraged.
@moyix, if you have any thoughts on this, that would be very helpful.

**Comment by jesings** [comment]
In the end, most of the CoW stuff in the kernel needed to be modified so we needed to copy and modify existing kernel functionality into the LKM. Initial performance results show around a 300x(?!) performance increase for mappings which don't have many pages written to them, and around a 60x performance increase for mappings with every page written. Currently, the LKM is in a state where it's nearly ready for testing, it can handle swapped out pages no problem.

Currently, the only 2 things I want to handle before that gets done is

1. making sure I haven't introduced some huge vulnerabilities, and
2. handling memory pressure conditions

Ideally, when the kernel doesn't have enough memory to complete an operation it undoes everything it's done. This is not terribly easy to do cleanly for us, because for example fork handles this case through destroying the whole child memory map which isn't possible for us to do. Munmap is a reasonable solution, however it itself can allocate internal memory for various edge cases which we may or may not need to handle for lind's fork, but which are definitely necessary for more robust CoW functionality when there is significant memory pressure. It seems that a suitable enough solution for wiping our written page table segments can be found unmap_region which we can modify in our LKM, but it probably will take a little more work to get a full solution that for example removes the vmas from the rbtree and completely undoes everything the call did before the kernel ran out of memory.

**Comment by JustinCappos** [comment]
Is this when there is a lack of physical memory or virtual address space?

**Comment by jesings** [comment]
This is when physical memory is starved

**Comment by jesings** [comment]
It seems that the only case that munmap will allocate memory is if a vma is split. If we avoid merging vmas until afterwards, we can use munmap to unmap without splitting.

**Comment by rennergade** [comment]
That sounds great. Should make this less of a headache.

**Comment by jesings** [comment]
I have patched the finished CoW fork into NaCl, and gathered some metrics on its performance. 

# Comparisons

In most cases, fork is not the bottleneck, and in such cases, as expected, we do not see much change in performance. 

## Comparisons to the previous NaCl implementation

In many bash tests (such as calling `factor` 100 times or doing other things to make bash fork/exec many times in a rapid interval),  we often gain around a 2x speed increase in overall execution time. Interestingly, calling `date` that many times yields a 2x speed *decrease* with the CoW fork, although I'm not sure why, as the executable shouldn't matter as it lies on the other side of an exec.
In the case of just forking with a very small executable (I reprised my previous test which just forks from every process to a fork depth of 8 [meaning 511 times]), we can also get around a 2x speed increase in overall execution time, although some information on the flame graphs seems to suggest that performance is being bottlenecked more by lock contention here (unsurprising given the number of processes active).
In order to test cases where the CoW fork really shines, I modified a test I had used previously which called fork many times, and added a 512MB static array to the file. This test was basically unable to complete in NaCl without CoW as the script kept timing it out after over 10 seconds, whereas with CoW it ran in around a fifth of a second discounting startup time. This test is promising as it is not dissimilar from a large program forking before exec'ing. In the case where we rewrite over the whole array in the child (but with many fewer forks), the CoW implementation is around 1.5 times slower than the previous one (as to be expected because of faulting).

## Comparisons to native

In most fork-bound cases, we are still significantly slower than native. As a note, in all these results I discount NaCl startup time.
Largely, the results follow the rule that when non-copy time in fork is mostly amortized (i.e. the 512MB case and similar ones), we're around 10-20x slower in Lind discounting startup time.
In other cases where non-copy time in fork is amortized, such as bash, we're around 20-50x slower in lind, however a great deal of this is spent in exec.
In cases where non-copy time in fork is not amortized (small programs), we're around 100x slower in lind.
In terms of just the fork call, for bash it runs around 5x slower than native in the worst case, and for most cases it runs within 3x of native, often at only around 2x slower. The more disjoint memory regions, the greater the discrepancy. Compared to the previous fork implementation, it runs at around 100x faster if there is any significant amount of memory copying involved.

# Upshot

**However**, except for that last case, fork is not a significant component of the execution time spent, except perhaps for one part, at least as far as flame graphs can show.
This part is the spawning of the worker thread(s) that are used for safeposix RPC, which in many cases makes fork take significantly longer (rather than spawning 1 thread, it spawns 2 or sometimes 3). This will be removed along with safeposix, and likely should make fork about as good as it's going to get with our architecture. Overall, I think at this point that there is not much left to be done with fork in lind, and that we should look elsewhere for further gains at this point, as I am satisfied with the progress I have made on it.

**Comment by rennergade** [comment]
@jesings it seems we're ready to do this now. Can you write down some directions for loading, merging, and testing?

Has the CoW branch been merged with the more recent develop changes?

**Comment by jesings** [comment]
Good news! After over a half year of mostly inactivity on this front, we have finally implemented CoW fork on the server, and nothing has crashed, and the lind unit tests have all passed with it implemented!
Before merging it to develop however, we will definitely want to implement a fallback codepath for in case the LKM isn't loaded. This should be doable however I'm not sure which of the following approaches better suits our use case: using a preprocessor define to say at compile time whether to use the LKM or not, or testing whether the LKM is present at initialization (by calling the syscall I hooked into with the CoW flag and seeing if it fails) and then setting a global flag to say whether to use the LKM at runtime?
I@JustinCappos and @moyix, what are your thoughts?

**Comment by JustinCappos** [comment]
I don't really have a strong preference for which one.  Just make sure you have a clear error message if things don't work.  Also, it should always be clear which one you are using.  It should not be possible for you to generate results where you think you are using the LKM but you ended up not doing so.

**Comment by rennergade** [comment]
Can finally close this one with the LKM merge. Congrats @jesings !

**Comment by JustinCappos** [comment]
I am fine with either, but there should be a way to tell Lind not to use
the LKM even if it is loaded.  It should also produce clear error messages
if it wants to use it and it is not running.  (We don't want to run some
experiments and then realize the module was or wasn't used when we thought
the opposite.)
