### ISSUE TITLE
Hook in Lstat for ls -l

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#168]
Per [this issue](https://github.com/Lind-Project/lind_project/issues/162), lstat isn't' currently working.

It seems like the infrastructure is there in glibc and native client, but isn't properly intercepting.

**Comment by kapkic** [comment]
@youngfalcon these might be useful
ls's source code is at ~/lind_project/tests/applications/coreutils/src/ls.c
These are the parameters that gave errors (segfault or different errors):
```
-l (long_format)
-c
-d
--file-type
-g
-i 
-n
-p
-o
-t
-u
-R
-S
-F
-s
```
Although some of them were due to the errnos weren't being processed currently which Nick made a PR for that. But the -l still gave segfaults/error.
