### ISSUE TITLE
Move from Travis to GitHub Actions

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#169]
Travis is no longer free and hasn't worked since the summer. Let's move our CI to GitHub Actions:

https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by rennergade** [comment]
Per meeting with @kapkic today. 

We want Actions to:

1. Pull lind:latest from dockerhub
2. Update all branches to develop (eventually will make this for PR's so repo w/ PR goes to merging branch)
3. Build full
4. Run `make test`

**Comment by kapkic** [comment]
We're able to run github-actions for CI/CD.
Config file: https://github.com/kapkic/lind_project/blob/develop/.github/workflows/container-selfhost.yml

On any pushes on develop (or manual dispatches):
- Pulls lind from dockerhub, runs with required arguments. 
- Pulls and installs `develop` branches of NaCl, rustposix, lind-glibc and lind_project.
    - Also it runs whenever a PR is made to `develop` branch, testing that PR branch with `develop` branches of other repos to ensure integration.
- Runs make test.

We're able to run this on our self-hosted machines and on github hosted machines (free of charge, but only has 14 GB's of space, so not reliable)

A working test run: https://github.com/kapkic/lind_project/runs/4676539008?check_suite_focus=true
Minor issue: Forkandopen is failing at test, otherwise everything is running as intended.

**Comment by kapkic** [comment]
Implemented with #119 .
