### ISSUE TITLE
Repy Memory Checking

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#22]
At this point there isn't really a good way to check if the memory being allocated in SafePOSIX is contained in the NaCl bounded memory address space. It will help us prove correctness if we could manage this.

**Comment by JustinCappos** [comment]
The cage's memory is easy to track, but Python also allocates memory.
Perhaps there is a trick we can do to make it leave the cage space alone.

For example, I wonder if we could cause the memory allocator to think that
all of the cage memory was already allocated by rewriting the malloc linked
list so that the last region ends with the end of the repy/NaCl address
space?

**Comment by rennergade** [comment]
Per meeting last week:

A good way to check this is to get the beginning and end Mem. Addresses for each/all cages (still not sure if they cages are contiguously aligned). Then in SafePOSIX, run a `while True:` loop that allocates memory, and check if any of the memory allocated is in that range(s).

**Comment by rennergade** [comment]
I have a better grasp of how NaCl's memory structure works at this point along with how SafePOSIX is working. Their memory spaces are separate and I don't see any issues here.

I'm going to close this issue for now.
