### ISSUE TITLE
Collect Popular Paths Data

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#258]
At this point @TristanB22 has created a script to collect pop paths data and has been running gcov. He is going to collect:

Popular Paths - via the script
and Reachable Paths - which is pop paths + trinity + LTP + reboot

He seems to be having some issues with reboot, which he'll comment on here

**Comment by TristanB22** [comment]
I have been having some weird things happening when I try to get the data together for the popular paths. Here is my process:

1) I reset the data
2) I run the popular paths script
3) I collect the popular paths gcov kernel data using "sudo lcov --capture --output-file ./kernel.info && genhtml ./kernel.info" in a directory of its own. This is dataset 1.
4) I run trinity and the linux test project
5) I collect this data using the same command above in a new data directory. This is dataset 2.
6) I reboot the computer.
7) I use the above command and collect the data a third time in a new directory. This is dataset 3.

Here is my issue:
Files and data are disappearing with the reboot. For example, dataset 1 is a complete subset of dataset 2. But, dataset 3 doesn't contain all of the data from datasets 1 and 2. Random files go missing and random data is reset (like, some of the lines of code that were marked as executed suddenly changed to unexecuted). Do you know why this could be happening?

**Comment by detectivelyw** [comment]
I think what you have seen is normal behavior of the kernel profiling. 
1) "dataset 1 is a complete subset of dataset 2": this is because the gcov data collecting is continuous and accumulative, unless you reset the counter or reboot. 
2) When you reboot, because of the randomness (background activities, kernel scheduling, I/O activities, etc.) it is expected that each run will have unique and slightly different kernel foot print. This explains why you have "some of the lines of code that were marked as executed suddenly changed to unexecuted". That being said, I believe the lines changed should be really tiny portion of the entire profile, meaning the majority of the kernel profile should be identical, with very tiny differences for each different run. 

For the Pop-Path experiment and kernel profiling, the method we used in our previous study and Lind paper was to do a "union" of the kernel lines executed for all the runs. The resulted "Popular-Paths" data was a approximation of the "popular lines" being used. Because of the randomness, the "Popular-Paths" will never be 100% precise I think. But, scientifically, our method should be good enough. 

Hope this helps with your questions.

**Comment by rennergade** [comment]
@detectivelyw I think your advice to do a union here makes a lot of sense. But we're still kind of confused how a reboot would actually delete data from an ongoing run. Do you have any recollection of that?

or @moyix does that sound familiar?

**Comment by detectivelyw** [comment]
"we're still kind of confused how a reboot would actually delete data from an ongoing run" I did not remember running into this problem. What data were being deleted? Could you back-up the data before rebooting?

**Comment by detectivelyw** [comment]
Are you referring to the gcda files? I don't think rebooting would affect the data collection. Because you can copy & store all the data in your own user directory right before rebooting. After reboot, just collect new dataset. And then eventually "union" all the datasets should give you the results.

**Comment by rennergade** [comment]
Yeah, the gcda files. We should be able to do what you're referencing, basically taking a pre-reboot dataset, and reboot dataset and union the two. Seems like that will work.

I still am wondering _why_ files and lines from files disappear on reboot though. Can't really find any reference to that anywhere.

**Comment by rennergade** [comment]
@detectivelyw Do you remember what method you used to union the datasets? Did you do this with the gcov data or after your ran it through the analyzer?

**Comment by rennergade** [comment]
@TristanB22 is reporting these numbers.

**Reachable Paths**
Lines - 30.1%
450659 of 1499050 lines
Functions - 34.8%
36203 of 104158 functions

**Popular Paths**
Lines - 11.9%
163213 of 1369279 lines
Functions - 13.2%
12651 of 95517 functions

**Comment by rennergade** [comment]
This is uploaded to google drive and the server. Will post the next step for @TristanB22 to compare again known vulns shortly.
