### ISSUE TITLE
Add Tests for Syscalls w/o Them

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#302]
We've implemented a ton of syscalls in nacl/rustposix. They are located [here](https://github.com/Lind-Project/safeposix-rust/tree/develop/src/safeposix/syscalls). However, we haven't created test cases for all of them.

@kpan2034 can you look through the syscall folder in RustPOSIX and the [test_cases](https://github.com/Lind-Project/lind_project/tree/develop/tests/test_cases) folder in tests and find what syscalls we haven't written tests for and list them here in this issue?

After that you can work on implementing some of them for the test suite.

**Comment by kpan2034** [comment]
Here's the list of syscalls in RustPOSIX that I couldn't find corresponding tests for in the test_cases folder:

- access
- creat
- flock
- fstatfs
- getifaddrs
- getpeername
- getppid
- getsockname
- getsockopt
- mkdir
- mknod
- pipe2
- poll
- rmdir
- setsockopt
- statfs


I'll start implementing the tests for them.

**Comment by kpan2034** [comment]
I've got the following tests running in Lind:

- pipe2
- getifaddrs
- getppid
- mkdir
- rmdir
- access


You can find the PR for this here: https://github.com/Lind-Project/lind_project/pull/306

There's still the issue of relative paths that I'm facing - files in the `testfiles` folder are not being picked up by a running program.
For now, I've used a workaround by creating temporary files in the same folder as the test. Nick suspects that it's because I'm running these test cases outside of the test suite.

There are some issues I'm facing for the rest of the tests which I've documented below.

- `mknod`: syscall not implemented
This is because we are yet to add an interface for the `mknod` syscall with glibc and NaCl.

- `flock`: It's throwing an invalid argument error (EINVAL), which is unexpected. This will require debugging at the RustPOSIX layer.

- `getpeername`/`getsockname`/`getsockopt`: the last one is causing a thread panic before exiting. This will require some digging into. (Note that the other two seem to be working correctly)

- `fstatfs`: error opening file: No such file or directory.
This is likely due to the issue mentioned above regarding relative paths.

- `statfs`: This runs without error, but I need to check whether the output that is returned is correct (currently the result is `0`).

- `rmdir`: While this test does work now, I found something while debugging the relative path issue (just documenting this here)

When the path does not exist, `rmdir` returns `EEXIST` (Path Exists) error.

I checked the `safeposix` repo, and indeed the rmdir syscall is returning `Errno::EEXIST`. I believe this should be `Errno::ENOENT`. 

You can find the exact line of code here: https://github.com/Lind-Project/safeposix-rust/blob/6d1e0d6e7963d2b7894c1a1f35e177f11c2ca7d7/src/safeposix/syscalls/fs_calls.rs#L1698

**Comment by rennergade** [comment]
Awesome, thanks @kpan2034. 

I'd like to assign the above to you guys as follows:

@kpan2034 - finish adding the working tests with your PR to the test suite, debug the flock issue + add test
@yizhuoliang - debug the getpeername/getsockname/getsockopt issue, add test
@Yaxuan-w - debug the fstatfs/statfs issue, add test 

@kuzeyardabulut add the mknod libc/nacl pathways, debug mknod, add test

**Comment by rennergade** [comment]
Also seems like we still need poll, @kuzeyardabulut maybe you should start with adding a poll test, may be a more incremental first step

**Comment by Yaxuan-w** [comment]
Here're syscalls I couldn't find corresponding tests under safeposix/tests folder:
* fstatfs
* mmap
* munmap
* getppid
* getpid
* flock
* epoll_create
* epoll_ctl
* epoll_wait
* pipe2
* getifaddrs

**Comment by kpan2034** [comment]
> @kpan2034 - finish adding the working tests with your PR to the test suite, debug the flock issue + add test @yizhuoliang - debug the getpeername/getsockname/getsockopt issue, add test @Yaxuan-w - debug the fstatfs/statfs issue, add test
> 
> @kuzeyardabulut add the mknod libc/nacl pathways, debug mknod, add test

Alright. Let me share the `getpeername/getsockname/getsockopt`, `fstatfs/statfs` and `mknod` tests I have so far with them on a different branch.  Once they are fixed we can merge to this one before merging to `dev`.

**Comment by kpan2034** [comment]
@yizhuoliang @Yaxuan-w @kuzeyardabulut 

I've added the code for the test cases that still require debugging in this branch: [feature/new-tests-to-debug](https://github.com/Lind-Project/lind_project/tree/feature/new-tests-to-debug)

**Comment by kpan2034** [comment]
> Here're syscalls I couldn't find corresponding tests under safeposix/tests folder:
> 
> * fstatfs
> * mmap
> * munmap
> * getppid
> * getpid
> * flock
> * epoll_create
> * epoll_ctl
> * epoll_wait
> * pipe2
> * getifaddrs

What branch are you looking at? The ones I've added should be in [feature/new-syscall-tests-cases](https://github.com/Lind-Project/lind_project/tree/feature/new-syscall-tests-cases), while the existing tests should be in the `develop` branch.

For e.g. The `mmap/munmap` test is here: [tests/test_cases/mmaptest.c](https://github.com/Lind-Project/lind_project/blob/develop/tests/test_cases/mmaptest.c).

**Comment by Yaxuan-w** [comment]
> > Here're syscalls I couldn't find corresponding tests under safeposix/tests folder:
> > 
> > * fstatfs
> > * mmap
> > * munmap
> > * getppid
> > * getpid
> > * flock
> > * epoll_create
> > * epoll_ctl
> > * epoll_wait
> > * pipe2
> > * getifaddrs
> 
> What branch are you looking at? The ones I've added should be in [feature/new-syscall-tests-cases](https://github.com/Lind-Project/lind_project/tree/feature/new-syscall-tests-cases), while the existing tests should be in the `develop` branch.
> 
> For e.g. The `mmap/munmap` test is here: [tests/test_cases/mmaptest.c](https://github.com/Lind-Project/lind_project/blob/develop/tests/test_cases/mmaptest.c).

I'm looking at rustposix test suite (https://github.com/Lind-Project/safeposix-rust/tree/develop/src/tests)

**Comment by Yaxuan-w** [comment]
The fstatfs test works as expected. statfs test case can run successfully but all file entries can only return 0. I don't know how to let statfs get the file information as expected. The relevant code is in this branch: [tests-of-statfs-fstatfs](https://hub.docker.com/r/securesystemslab/lind). I've added those two tests to test suite.

**Comment by rennergade** [comment]
I believe this is done now with the recent PR.
