### ISSUE TITLE
libc.so versioning discrepancy on build

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#6]
Currently on a clean build, trying to run a `nacl-gcc` compiled nexe file will yield the following error:
`error while loading shared libraries: /lib/glibc/tls/libc.so.b7b14f88: cannot read file data: Error 9`

The LindFS is populated with `/lib/glibc/libc.so.990e7c45` and `/lib/glibc/32/libc.so.990e7c45` which lines up with the commit version in the up to date version at: https://github.com/Lind-Project/native_client/blob/lind/tools/REVISIONS

However, the compiled nexe's are requesting a libc.so commit that is a seemingly random, from a short period in 2013: https://github.com/Lind-Project/native_client/commit/2fb46f07cb18fd46479729e3162acafa5e1f5ed6#diff-f55637873e2d1ef5a5cee5a266a7d956

This needs to be traced to determine why they are requesting that version. I can't find any hard-coded references to that commit anywhere in the organization.

**Comment by jesings** [comment]
The file libc.so.b7b14f88 is not regenerated when glibc is recompiled (nor when native client is recompiled.

**Comment by jesings** [comment]
In order to get lind to run, and not show an error that it was missing the libc.so.b7b14f88 file, it was needed to run the following sequence of commands
`mkdir /home/lind/lib/glibc/32 -p
cp /home/lind/lind_project/src/native_client/toolchain/linux_x86/x86_64-nacl/lib32/libc.so.b7b14f88 /home/lind/lib/glibc/32
cp /home/lind/lind_project/src/native_client/tools/out/nacl-sdk/x86_64-nacl/lib32/runnable-ld.so /home/lind/lib/glibc/32
cp /home/lind/lind_project/src/native_client/toolchain/linux_x86/x86_64-nacl/lib/libc.so.b7b14f88 /home/lind/lib/glibc/
cp /home/lind/lind_project/src/native_client/tools/out/nacl-sdk/x86_64-nacl/lib/runnable-ld.so /home/lind/lib/glibc/

python2 lind_fs_utils.py cp /home/lind/ lib/glibc/libc.so.b7b14f88
python2 lind_fs_utils.py cp /home/lind/ lib/glibc/runnable-ld.so
python2 lind_fs_utils.py cp /home/lind/ lib/glibc/32/libc.so.b7b14f88
python2 lind_fs_utils.py cp /home/lind/ lib/glibc/32/runnable-ld.so

rm -rf /home/lind/lib
`

**Comment by rennergade** [comment]
It seems that the commit hash generated in files in `native_client/toolchain` which is downloaded externally disagree with the commit hash in `native_client/tools/BUILD` which is our build directory where `glibc` etc are symlinked into.

For example, when grepping for `LD_NACL_X86_64_SO`:
`lind_project/native_client/toolchain/linux_x86/x86_64-nacl/include/gnu/lib-names.h:# define LD_NACL_X86_64_SO              "ld-nacl-x86-64.so.b7b14f88"`
`lind_project/native_client/tools/BUILD/build-glibc32/gnu/lib-names.h:# define LD_NACL_X86_64_SO              "ld-nacl-x86-64.so.990e7c45"`

**Comment by rennergade** [comment]
It turns out that our desired version of `nacl-gcc` is generated in `native_client/tools/out`, while there is also one that's generated in the `native_client/toolchain` directory.

Though this is a bit confusing, and the `toolchain` build process may desirably be removed to stop wasting time/space, switching to the correct gcc implementation fixes this issue.
