### ISSUE TITLE
NaCl Fork Overhead

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#67]
Currently, the Fork system call is taking a huge chunk of time that overshadows execution time for small programs and large pipelines. 90+% of fork is from the NaClCopyExecutionContext function which copies context between processes, roughly two-thirds of that function is composed of `memmove`'s.

This seemingly is because we're losing the CopyOnWrite semantics that a native fork would have. Can we re-implement this to utilize CopyOnWrite?

![perf-kernel](https://user-images.githubusercontent.com/7719272/83190977-4e5d5480-a101-11ea-9253-8b4d88c25d71.png)

**Comment by JustinCappos** [comment]
@jesings mentioned to me: I think what I was talking about for the MAP_SHARED and MAP_ANONYMOUS solution, the memfd_create syscall, is handled nearly the same way in ram as a shared memory object except it doesn't create a file entry (except in /proc) associated with it, so it should be superior to a shmget system call

I think this should work better than the shared memory solution I was pushing in the meeting.  Regardless, we definitely shouldn't need to create a RAM FS backed file or something else that actually lives on a FS somewhere.  Let's try these out and see how they work!

**Comment by jesings** [comment]
So I've been looking at potential solutions to COW for fork, and I have a couple of pieces of input:
1. In order to do the MAP_ANONYMOUS/MAP_SHARED solution, I would need to have parts of process memory in some object referred to by an fd (say a memory object made by memfd_create). I'm not sure how to do that without copying the memory over which would defeat the purpose of COW
2. I think it might also be worth looking into a different solution, although I doubt it will work, involving the clone3 system call (which is used to implement pthreads but which we probably shouldn't work with directly, as we want lots of the things that pthreads offers us). It seems like there is a way (by specifying CLONE_THREAD and not specifying CLONE_VM in the flags) that you can create a new thread in the same process that has its memory as COW. Perhaps there is some way to access this from pthreads? If so, I couldn't find it.

**Comment by jesings** [comment]
Ah I just looked a little deeper into the man page for clone3, and it says
```
Since Linux 2.5.35, the flags mask must also include CLONE_SIGHAND if CLONE_THREAD is specified (and note that, since Linux 2.6.0, CLONE_SIGHAND also requires CLONE_VM to be included).
```
So it looks like we can't use CLONE_THREAD without CLONE_VM

**Comment by rennergade** [comment]
I wanted to get some real performance stats for Jonathan so I hacked bash to get time statistics for the fork() call with real workloads.

Natively we're seeing fork take 80us on average
while with Lind we're seeing 160 ms

So Lind's fork is ~2000x slower currently.

**Comment by JustinCappos** [comment]
Okay, good to know.  Would be interested in seeing a finer grained breakdown too, if possible.  I know memory copying is the main thing, but what else is there if that is left out?

**Comment by jesings** [comment]
I've been doing a lot of work with splice, and I've implemented it and have been profiling it since yesterday. I don't think it's doing copy-on-write given some of the in-kernel calls that it's making, although why is not exactly clear given a separate problem we've been having which I will describe below. I may be able to mess with splice a little bit more in order to get true copy-on-write or at least some other better performance, but this is how it stands for now. The current flame graph for lscatwc is:
![image](https://user-images.githubusercontent.com/34111484/90060405-49dd1c80-dcaa-11ea-95c1-83133fdc34fc.png)
and it does run significantly faster than the memcpy solution (a little over .6 seconds when compared to a little over .7).
The problem I noticed is that a suspicious amount of time is being taken up in NaClPatchAddr (which in this image is shown as `NaClPa...`, and is towards the top-left of the sel_ldr section). After inspecting the actual code of NaClPatchAddr, the reason became much clearer:
```
static INLINE void NaClPatchAddr(uintptr_t child_bits, uintptr_t parent_bits, uintptr_t *start, size_t size) {
  size_t cnt = size / sizeof(uintptr_t);
  for (size_t i = 0; i < cnt; i++) {
    if ((start[i] & ~UNTRUSTED_ADDR_MASK) != parent_bits) {
      continue;
    }
    NaClLog(1, "patching %p\n", (void *)start[i]);
    /* clear upper bits */
    start[i] &= UNTRUSTED_ADDR_MASK;
    /* add child prefix */
    start[i] |= child_bits;
    NaClLog(1, "new addr %p\n", (void *)start[i]);
  }
}
```
It iterates over the whole memory that was copied and writes to any aligned pointers with cage bits in the upper half, which seems like it would incur a stupid amount of overhead, invalidate a lot of the good parts of copy-on-write, and also could potentially corrupt some legitimate data. This solution in general really doesn't sit well with me, but I can't really think of a better one. I can likely improve performance by manually vectorizing this pointer comparison operation, however I don't think that's really worth it. It would help me a lot to hear what other people have to say about any of this.

**Comment by jesings** [comment]
I think I have an idea of the culprit for why splice isn't doing mmu manipulation like it says it should
The wikipedia page for splice begins with the following
> splice() is a Linux-specific system call that moves data between a file descriptor and a pipe without a round trip to user space. The related system call vmsplice() moves or copies data between a pipe and user space. Ideally, splice and vmsplice work by remapping pages and do not actually copy any data, which may improve I/O performance. As linear addresses do not necessarily correspond to contiguous physical addresses, this may not be possible in all cases and on all hardware combinations.

The end is what I think the issue is:
> "As linear addresses do not necessarily correspond to contiguous physical addresses, this may not be possible in all cases and on all hardware combinations."

We're mapping a file that ends up at over 2 GB long, so I have a very hard time believing that the memory we splice would all be consecutive in physical memory. Additionally, it definitely is running a lot faster than an actual memcpy solution (despite having to context switch for every megabyte copied), so I do think that it is actually mmu manipulating for a lot of the pages but not others, and that would point to the issue being related to non-contiguity.
The solution I can think of for now is to make a bunch of smaller files as backing for memory rather than a single huge file. This might also have benefits in terms of actually freeing resources, but further complicates implementation.

**Comment by jesings** [comment]
@moyix if you have any input on my theory about why splice isn't working, we'd love to hear it.

**Comment by jesings** [comment]
I tested out my theory today, and pretty soundly debunked it. When we back the memory with 300 smaller files rather than 1 larger file, the program's behavior is unchanged, and it also runs slightly slower because more time is spent in pipe locks because more splices and vmsplices are being made, with each copying less data.

**Comment by jesings** [comment]
Good news and bad news:

First, the bad news:
I have been unable to make splice particularly performant, even outside of lind. I have been doing some tests on my own machine with vmsplice/splice and comparing it to memcpy. Vmsplice/splice is pretty much always slower for the amounts of memory we're working with, regardless of whether or not it's actually doing copy-on-write. This is mostly because on my host machine the vmsplice/splice solution seems to take tons of memory while splicing, forcing me to swap a fair bit (or in the case of my host machine zswap to compressed RAM). Although the actual program time is less, it's not that much less, being very similar to the reduced overhead we see in the NaCl solution which is significant but not orders of magnitude different. The reason we don't see so much overhead on the server is likely because it has more RAM, but if we really want to have multiple lind processes running at once, it wouldn't be great to increase memory pressure so much.
Here is the splice performance (just for the actual program runtime)
![image](https://user-images.githubusercontent.com/34111484/90459954-6a511080-e0c8-11ea-84c0-8c346bbbcecd.png)
As far as I can see, splice and vmsplice do seem to be almost entirely doing Copy-on-Write but are spending a ton of time on getting pages from the page cache or freeing them manually--likely because of the greatly increased memory pressure.
Memcpy did not suffer from those same memory pressure issues, and though the actual program time was longer, it ran in a much shorter amount of time because it didn't have to swap anything.
Here is the performance for memcpy (only program runtime):
![image](https://user-images.githubusercontent.com/34111484/90460281-21e62280-e0c9-11ea-9ab1-65727b235629.png)

But here's the good news:
I was digging through the kernel to see how splice was actually implemented and to look for how to set it to actually behave in a copy-on-write way. I then came upon a syscall that I had seen last week but had dismissed because of a line in its man page. This syscall is process_vm_writev (or process_vm_readv which is essentially the same syscall in the other direction). It is used to take memory from one process' address space and put it into another's. When I saw it last week, I assumed that it would be able to use the process' own pid to set it to copy from one part of its address space to the other, and was intrigued. However, when I saw in the man page's notes section that:
> These system calls were designed to permit fast message passing by allowing messages to be exchanged with a single copy operation (rather than the double copy that would be required when using, for example, shared memory or pipes).

I believed that this function could not behave in a zero-copy manner. I did see it in the wikipedia page for zero-copy but didn't put 2 and 2 together until I found some functions called by it in the kernel, in the same paths that splice would ideally go down if it were doing copy-on-write. I added this in to the test on my own machine and it ran blisteringly fast compared to the other implementations: (still only including program time)
![image](https://user-images.githubusercontent.com/34111484/90460872-7c33b300-e0ca-11ea-88df-fb8dc044b363.png)
Luckily for me, its interface as a vectored uio syscall is very similar to that for vmsplice, so I get to feel like my work over the past couple weeks wasn't entirely wasted. I should be able to create a working implementation tomorrow that can test if this works well in Lind.

**Comment by rennergade** [comment]
This sounds really promising. Awesome work!

**Comment by jesings** [comment]
New developments:
I implemented a fork using process_vm_writev, and it ran slower than the splice fork but faster than the memcpy fork. This was not at all the behavior I was expecting, so I spent a while gathering data about it. Here is a flame graph for it:
![image](https://user-images.githubusercontent.com/34111484/90564026-48a86580-e16a-11ea-8b1d-1be5b27d312b.png)
I noticed one crucial thing about this flame graph: a significant amount of time in the process_vm_writev was being taken up by shared memory operations.
![image](https://user-images.githubusercontent.com/34111484/90564217-9b821d00-e16a-11ea-8d0d-f23038e727f3.png)
I had seen shared memory operations in the splice fork, but I had assumed that they were the write operations to the memfd (which uses the shared memory write and read inside the kernel). This assumption was somewhat reinforced when I took a test of splice using a temp file (in an ext4 file system) as the backing memory last week:
![image](https://user-images.githubusercontent.com/34111484/90565248-3a5b4900-e16c-11ea-95b1-5cf01e4d04b9.png)
The shared memory operations in a splice to a memfd were replaced by ext4 operations, making me think that nothing out of the ordinary was happening.
However the fact that these shared memory operations (i.e. shmem_fault) are happening in process_vm_writev leads me to suspect that there's something more to this.
One of the things I knew was happening in my splice implementation is that every entry in the page table was being copied, even those explicitly marked as map_shared. I was going to leave this optimization for later, but now I have reason to believe it may well be the cause of some significant slowdowns in process_vm_writev and splice performance. A fair amount of memory in the memory maps of the Lind tests I was running was taken up by shared memory mappings of files like this one: `/dev/shm/google-nacl-shm--12671.1`. These are being fully copied each time, which is not only incorrect behavior but is something I believe may be tanking performance of splice and  process_vm_writev. The primary implementation issue is that there is no information about what file each entry in the NaCl page table corresponds to. The fact that it's unlinked shouldn't matter if there is still an open file handle to it. I will talk with @rennergade about the best way to go about tackling this issue, and if @moyix or @JustinCappos have any thoughts on any of this, it would be great to hear from them.

**Comment by jesings** [comment]
I talked to @rennergade and we looked for where these shared memory regions are actually getting mapped. We both agreed that eventually we will need to attach the file descriptor to the vmmap entry so that forked processes can actually share MAP_SHARED segments like is specified by POSIX. However, I figured out a different solution for the mean time that improves fork performance. The NaClApp stores a text_shm member, which is a pointer to a NaCl shared memory descriptor, which is equivalent to the desc field of the /dev/shm/google-nacl-shm--12671.1 entry in the NaCl vmmap, so I compared each entry's desc field to this value, and if it was not equal, I skipped the copying and patching. This page table entry is 1 GB long and mostly consists of pages that are actually mapped as PROT_NONE on the host machine although the whole vmmap entry is listed as being mapped as PROT_RX. This means we were copying and patching a huge amount of unnecessary data. This also seems to be the source of the shmem_fault program time--I believe it was in changing the shared memory file's mappings from PROT_NONE to PROT_RX. 
Here are the performance statistics:
- The original memcpy version runs as follows:
```
@(2:476) $ time lind -t /bin/bash lscatwc
executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash lscatwc]
Lind v1.0-rc2
Opening file system...
done.
[914,953295936:10:16:08.933762] BYPASSING ALL ACL CHECKS
      5       5      34
[TimeInfo] NaCl main program time spent = 0.633700
[TimeInfo] NaCl initialization time spent = 0.092144
[TimeInfo] NaCl user program time spent = 0.541541
Persisting metadata: ...
Done persisting metadata.
Terminated
real    0m0.682s
user    0m0.444s
sys     0m0.270s
```
- The new splice version runs as follows:
```
@(2:476) $ time lind -t /bin/bash lscatwc
executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash lscatwc]
Lind v1.0-rc2
Opening file system...
done.
[6416,610423872:10:36:03.540575] BYPASSING ALL ACL CHECKS
      5       5      34
[TimeInfo] NaCl main program time spent = 0.222044
[TimeInfo] NaCl initialization time spent = 0.091623
[TimeInfo] NaCl user program time spent = 0.130329
Persisting metadata: ...
Done persisting metadata.
Terminated
real    0m0.239s
user    0m0.223s
sys     0m0.047s
```
- The new process_vm_write version runs as follows:
```
executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash lscatwc]
Lind v1.0-rc2
Opening file system...
done.
[7503,3873137728:10:48:20.610146] BYPASSING ALL ACL CHECKS
      5       5      34
[TimeInfo] NaCl main program time spent = 0.221416
[TimeInfo] NaCl initialization time spent = 0.092199
[TimeInfo] NaCl user program time spent = 0.129047
Persisting metadata: ...
Done persisting metadata.
Terminated
real    0m0.241s
user    0m0.230s
sys     0m0.038s
```
The splice and process_vm_write versions are roughly equivalent in performance, but I think the process_vm_write version is preferred because of its simpler API and its lack of a backing file, leading to resources being more easily freed. The downside is that splice is an older and more established syscall, and may be more portable, although I think neither are portable at all, both being listed as linux specific on their admittedly horrendously written manpages.
The flame graphs for the performance of the program with splice and process_vm_write are the following:
![image](https://user-images.githubusercontent.com/34111484/90694470-47e10380-e23e-11ea-84df-264af202d387.png)
![image](https://user-images.githubusercontent.com/34111484/90694548-69da8600-e23e-11ea-9c06-2a5acaa16436.png)
I'm really glad to have this done in time for the meeting tomorrow.

**Comment by jesings** [comment]
I have fixed the fork depth issue that I found in the new version of fork which was caused by an eventual stack overflow due to caching information during fork. I gathered some final performance statistics about the new CoW version of fork. It appears to be something like a 10 times speedup from the previous implementation, which is still unfortunately much slower than a native fork. However, the sources of this slowdown are at least much more straightforward now:

1. We are copying more pages (because NaCl uses more memory for bookkeeping and other things) than native does so `vm_writev` is significantly slower than the native fork. `vm_writev` takes slightly over 1/3 of the total time of fork
2. We reload the executable on each fork in order to obey NaCl's memory guarantees and pointer bounding. The function `NaClLoadFileAslr` takes slightly less than 1/3 of the total fork time, primarily in the function `NaClValidateCode` which calls `ValidateChunkAMD64` which I believe (at first glance, I haven't gone that deep into analyzing it) iterates over the whole executable and ensures that it obeys NaCl's memory guarantees. We may be able to eliminate this cost by telling whether the executable has already been validated, but we may not.
3. Around 1/4 of the time is in `NaClCopyDynamicText,` some for actually copying dynamic text, but the vast majority for `NaClPatchAddr`, which we've discussed earlier. This time, as far as we can tell, would not be easy to remove or eliminate while maintaining NaCl's guarantees about address space isolation.

We may be able to reduce some of this time by copying the stack only up to the stack pointer, but that's unlikely to be an order of magnitude improvement and might even be negligible. So this is probably around the best we're going to get for fork for now. Looking forward to getting this implementation merged in!

Data:

Non-CoW:
![flame2](https://user-images.githubusercontent.com/34111484/96042709-7260ce80-0e33-11eb-83e4-f2c024a50419.png)
CoW:
![flame1](https://user-images.githubusercontent.com/34111484/96042688-696ffd00-0e33-11eb-9765-bd5d1f7c01df.png)

Non-CoW:
```
(ins)(2:1387) $ time lind -t /bin/bash -c "ls & echo test & dir"

executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash -c ls & echo test & dir]
Lind v1.0-rc2
Opening file system...
done.
[1864,221680704:09:55:07.233237] BYPASSING ALL ACL CHECKS
[ERROR][dispatch] Failed to look up 29 with error 29
/bin/bash: //.bashrc: Bad file descriptor
timing forkwrite msec: 188 ms
bin
dev
lib
timing forktiming forkwrite msec: 138 ms
test
timing forktiming forktiming forkwrite msec: 117 ms
bin  dev  lib
timing forktiming forktiming fork[TimeInfo] NaCl main program time spent = 0.650609
[TimeInfo] NaCl initialization time spent = 0.092339
[TimeInfo] NaCl user program time spent = 0.558254
Persisting metadata: ...
Done persisting metadata.
Terminated

real    0m0.667s
user    0m0.430s
sys     0m0.300s
```
CoW:
```
(ins)(2:1387) $ time lind -t /bin/bash -c "ls & echo test & dir"

executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash -c ls & echo test & dir]
Lind v1.0-rc2
Opening file system...
done.
[876,3300222016:09:53:11.509390] BYPASSING ALL ACL CHECKS
/bin/bash: //.bashrc: Bad file descriptor
timing forkwrite msec: 11 ms
timing forktiming forkwrite msec: 20 ms
test
bin
dev
lib
timing forktiming forktiming forkwrite msec: 17 ms
bin  dev  lib
timing forktiming forktiming fork[TimeInfo] NaCl main program time spent = 0.242784
[TimeInfo] NaCl initialization time spent = 0.092222
[TimeInfo] NaCl user program time spent = 0.150526
Persisting metadata: ...
Done persisting metadata.
Terminated

real    0m0.233s
user    0m0.226s
sys     0m0.062s
```

Non-CoW:
```
@(2:2289) $ lind -t /bin/bash -c 'i=0; while [[ "$i" -lt 100 ]]; do i=$(($i+1)); (factor $i) & done;'

executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash -c i=0; while [[ "$i" -lt 100 ]]; do i=$(($i+1)); (factor $i) & done;]
Lind v1.0-rc2
Opening file system...
done.
[2670,1328026688:10:45:28.543699] BYPASSING ALL ACL CHECKS
[ERROR][dispatch] Failed to look up 29 with error 29
/bin/bash: //.bashrc: Bad file descriptor
timing forkwrite msec: 193 ms
1:
timing forktiming forkwrite msec: 122 ms
2: 2
timing forktiming forktiming forkwrite msec: 120 ms
3: 3
...
[TimeInfo] NaCl main program time spent = 14.264195
[TimeInfo] NaCl initialization time spent = 0.093447
[TimeInfo] NaCl user program time spent = 14.170701
Persisting metadata: ...
Done persisting metadata.
Terminated
```
CoW:
```
@(2:2290) $ lind -t /bin/bash -c 'i=0; while [[ "$i" -lt 100 ]]; do i=$(($i+1)); (factor $i) & done;'

executing: [sel_ldr -a -t -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /bin/bash -c i=0; while [[ "$i" -lt 100 ]]; do i=$(($i+1)); (factor $i) & done;]
Lind v1.0-rc2
Opening file system...
done.
[4268,3328635968:10:47:36.799348] BYPASSING ALL ACL CHECKS
/bin/bash: //.bashrc: Bad file descriptor
timing forkwrite msec: 11 ms
1:
timing forktiming forkwrite msec: 10 ms
2: 2
timing forktiming forktiming forkwrite msec: 9 ms
3: 3
...
[TimeInfo] NaCl main program time spent = 5.361019
[TimeInfo] NaCl initialization time spent = 0.093153
[TimeInfo] NaCl user program time spent = 5.267819
Persisting metadata: ...
Done persisting metadata.
Terminated
```

**Comment by rennergade** [comment]
This is great!

The validation definitely seems like a place where we can make improvement, it seems silly to do that each fork. Other than that we'll probably have to live with some of this, its probably not possible to get super close to native performance.

**Comment by rennergade** [comment]
With that PR, the huge first steps of this are done. I'm going to close this issue as a milestone, but reference it in a new issue to further our efforts.

Great job @jesings !
